### GET all notes
GET http://localhost:3001/api/notes
content-type: application/json

### GET unkown endpoint
GET http://localhost:3001/api/loks
content-type: application/json

### GET single note
GET http://localhost:3001/api/notes/6575d986bf8cc01f1ded7289


### DELETE single note
DELETE http://localhost:3001/api/notes/65748bb94bd663f649098115

### ADD single note
POST http://localhost:3001/api/notes/
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpbyIsImlkIjoiNjU5NDJhMTBhNjcxNDQ5NmUxNmQ3YTUwIiwiaWF0IjoxNzA0MjkyMjA3fQ.81CSG5MjXHk2fz5ZnviV7KtN4GwLmy_bkQIl7_okgA8

{
    "content": "JWT new!!",
    "important": true
}

### ADD invalid note - Error
POST http://localhost:3001/api/notes/
content-type: application/json

{
    "important": true
}

### Modify note
PUT  http://localhost:3001/api/notes/6575d986bf8cc01f1ded7289
content-type: application/json

{
    "content": "CHANGED!!!",
    "important": true
}